import { delta } from '@magic/utils/deepDelta';
import { DeepPartial } from 'ts-essentials';

import type { GetAnimatedSchema } from '.';
import type { EverySchemaPropName, SchemaId, ShapeName } from '../types';
import type { DefineTimeline } from './timeline/define.ts';
import type { LooseSchema, LooseSchemaValue } from './types';

export const AUTO_ANIMATE_DURATION_MS = 500;
/**
 * properties supported by the auto animate feature.
 *
 * ⚠️ **only properties listed here will be animated with `useAutoAnimate`**
 */
const AUTO_ANIMATED_PROPERTIES = new Set<EverySchemaPropName>([
  'at',
  'start',
  'end',
  'lineWidth',
  'radius',
  'fillColor',
]);

type LooseSchemaWithName = LooseSchema & { shapeName: ShapeName };
type StopperKey = `${SchemaId}-${string}`;

const clone = <T>(obj: T) => JSON.parse(JSON.stringify(obj)) as T;

export const useAutoAnimate = (
  defineTimeline: DefineTimeline,
  getAnimatedSchema: GetAnimatedSchema,
) => {
  let capturedSchemas: LooseSchemaWithName[] = [];
  let activelyCapturingSchemas = false;

  const snapshotMap: Map<
    SchemaId,
    Partial<{ before: LooseSchemaWithName; after: LooseSchemaWithName }>
  > = new Map();
  const animationStopper: Map<StopperKey, () => void> = new Map();

  const applyAnimation = (
    startVal: LooseSchemaValue,
    endVal: LooseSchemaValue,
    propName: EverySchemaPropName,
    id: SchemaId,
    shapeName: ShapeName,
  ) => {
    const stopKey: StopperKey = `${id}-${propName}`;
    const stopper = animationStopper.get(stopKey);
    if (stopper) stopper();

    const { play, stop } = defineTimeline({
      forShapes: [shapeName],
      durationMs: AUTO_ANIMATE_DURATION_MS,
      easing: { [propName]: 'in-out' },
      keyframes: [
        {
          progress: 0,
          properties: { [propName]: startVal },
        },
        {
          progress: 1,
          properties: { [propName]: endVal },
        },
      ],
    });

    play({ shapeId: id, runCount: 1 });
    animationStopper.set(stopKey, () => stop({ shapeId: id }));
  };

  return {
    captureSchemaState: (schema: LooseSchema, shapeName: ShapeName) => {
      if (!activelyCapturingSchemas) return;
      capturedSchemas.push(clone({ ...schema, shapeName }));
    },
    snapshotMap,

    /**
     * Captures a pair of "before" and "after" snapshots of the given shapes' schemas
     * by invoking the provided `flushDraw` function twice.
     *
     * This enables automatic animations to be generated by diffing the two states.
     *
     * @param ids - The IDs of shapes to track during this animation frame.
     * @param flushDraw - A function that triggers a draw cycle. This is called:
     *   - once immediately to capture the "before" state, and
     *   - again inside the returned `finalize()` function to capture the "after" state.
     *
     * @returns A function that, when called, finalizes the capture and triggers animation.
     *
     * @example
     * const finalize = autoAnimate.captureFrame(ids, () => draw());
     * mutateShapes();
     * finalize(); // triggers animation between captured states
     */
    captureFrame: (flushDraw: () => void) => {
      // clear any stale snapshots left over from previous abandoned frames
      snapshotMap.clear();

      const takeSnapshot = (state: 'before' | 'after') => {
        capturedSchemas = [];
        activelyCapturingSchemas = true;
        flushDraw();
        activelyCapturingSchemas = false;
        for (const schema of capturedSchemas) {
          const shapeSchemaEntry = snapshotMap.get(schema.id) ?? {};
          const liveSchema = getAnimatedSchema(schema.id);
          snapshotMap.set(schema.id, {
            ...shapeSchemaEntry,
            [state]: clone(liveSchema ?? schema),
          });
        }
      };

      takeSnapshot('before');

      return () => {
        takeSnapshot('after');

        const schemasCapturedInSnapshots = Array.from(snapshotMap).map(
          ([schemaId, snapshotStates]) => ({
            schemaId,
            beforeSchema: snapshotStates.before,
            afterSchema: snapshotStates.after,
          }),
        );

        for (const snapshot of schemasCapturedInSnapshots) {
          const { beforeSchema, afterSchema } = snapshot;

          // if a shape schema was added/removed during the snapshot
          // we are missing a start/end position for it, therefore it cannot be animated
          if (!beforeSchema || !afterSchema) continue;

          // if a shapes schema has not changed between snapshots, we dont need to animate it
          const schemaDifference: DeepPartial<LooseSchemaWithName> | null =
            delta(beforeSchema, afterSchema);
          if (!schemaDifference) continue;

          // animation between shapes is not supported
          const { shapeName } = schemaDifference;
          if (shapeName) {
            console.warn(
              `shape with ID ${snapshot.schemaId} transformed from a ${beforeSchema.shapeName} to an ${afterSchema.shapeName}. Animating between shapes is unsupported and breaks the engine, therefore auto-animate has ignored it`,
            );
            continue;
          }

          const schemaPropNames = Object.keys(
            schemaDifference,
          ) as EverySchemaPropName[];

          for (const propName of schemaPropNames) {
            // ignore all unsupported shape properties on the schema
            const schemaPropertySupported =
              AUTO_ANIMATED_PROPERTIES.has(propName);
            if (!schemaPropertySupported) continue;

            applyAnimation(
              beforeSchema[propName],
              afterSchema[propName],
              propName,
              afterSchema.id,
              afterSchema.shapeName,
            );
          }
        }

        snapshotMap.clear();
      };
    },
  };
};
