import { nullThrows } from '@core/utils/assert';
import { jsonClone } from '@core/utils/clone';
import { delta } from '@core/utils/delta/index';
import { DeepPartial } from 'ts-essentials';

import type {
  EverySchemaPropName,
  SchemaId,
  ShapeName,
} from '../../types/index.ts';
import type { GetAnimatedSchema } from '../index.ts';
import type { DefineTimeline, Timeline } from '../timeline/define.ts';
import type { LooseSchema, LooseSchemaValue } from '../types.ts';
import { arrowAdd } from './arrow/add.ts';
import { circleAdd } from './circle/add.ts';
import {
  AUTO_ANIMATED_PROPERTIES,
  AUTO_ANIMATE_DURATION_MS,
} from './constants.ts';
import { LooseSchemaWithName } from './types.ts';

type CreateTimelineValue = {
  startValue: LooseSchemaValue;
  endValue: LooseSchemaValue;
  schemaPropertyName: EverySchemaPropName;
};

type CaptureState = 'before' | 'after' | undefined;

export const createAutoAnimate = (
  defineTimeline: DefineTimeline,
  getAnimatedSchema: GetAnimatedSchema,
) => {
  let capturedSchemas: Map<SchemaId, LooseSchemaWithName> = new Map();
  let captureState: CaptureState;

  const snapshotMap: Map<
    SchemaId,
    Partial<{ before: LooseSchemaWithName; after: LooseSchemaWithName }>
  > = new Map();
  const shapeIdToAnimationStopper: Map<string, () => void> = new Map();

  const createTimeline = (
    shapeName: ShapeName,
    values: CreateTimelineValue[],
  ) => {
    const startingValues: Record<string, LooseSchemaValue> = {};
    const endingValues: Record<string, LooseSchemaValue> = {};

    for (const value of values) {
      startingValues[value.schemaPropertyName] = value.startValue;
      endingValues[value.schemaPropertyName] = value.endValue;
    }

    return {
      forShapes: [shapeName],
      durationMs: AUTO_ANIMATE_DURATION_MS,
      keyframes: [
        {
          progress: 0,
          properties: startingValues,
        },
        {
          progress: 1,
          properties: endingValues,
        },
      ],
    };
  };

  const runAnimation = (timeline: Timeline<any>, schemaId: string) => {
    const stopper = shapeIdToAnimationStopper.get(schemaId);
    stopper?.();

    const { play, stop } = defineTimeline(timeline);
    play({ shapeId: schemaId, runCount: 1 });
    shapeIdToAnimationStopper.set(schemaId, () => stop({ shapeId: schemaId }));
  };

  return {
    captureSchemaState: (schema: LooseSchema, shapeName: ShapeName) => {
      if (!captureState) return;
      // we only care about capturing each schema once, the rest of the calls should be ignored
      if (capturedSchemas.has(schema.id)) return;
      // if capture state is "before", use the shape's live (currently animating) schema instead, to prevent snap-backs.
      const liveSchema =
        captureState === 'before'
          ? (getAnimatedSchema(schema.id) ?? schema)
          : schema;
      const capturedSchema = jsonClone({ ...liveSchema, shapeName });
      capturedSchemas.set(schema.id, capturedSchema);

      // write into snapshotMap immediately (not after flushDraw finishes) so
      // getCaptureOverride sees this shape's entry within the same draw pass,
      // suppressing newly added shapes before they get a chance to flash.
      const shapeSchemaEntry = snapshotMap.get(schema.id) ?? {};
      snapshotMap.set(schema.id, {
        ...shapeSchemaEntry,
        [captureState]: capturedSchema,
      });
    },

    /**
     * While a capture window is open (between captureFrame's before/after snapshots),
     * shape rendering must not jump to live/mutated values or the transition
     * being diffed for animation will visibly pop. This freezes rendering on the
     * pre-mutation schema, or suppresses it entirely for a shape with no "before"
     * (i.e. one newly added during this capture).
     */
    getCaptureOverride: (
      schemaId: SchemaId,
    ): { schema: LooseSchemaWithName } | 'suppress' | undefined => {
      const snapshotMapEntry = snapshotMap.get(schemaId);
      if (!snapshotMapEntry) return undefined;

      const { before: beforeSnapshot } = snapshotMapEntry;
      if (!beforeSnapshot) return 'suppress';

      return { schema: beforeSnapshot };
    },

    /**
     * Captures a pair of "before" and "after" snapshots of the given shapes' schemas
     * by invoking the provided `flushDraw` function twice.
     *
     * This enables automatic animations to be generated by diffing the two states.
     *
     * @param ids - The IDs of shapes to track during this animation frame.
     * @param flushDraw - A function that triggers a draw cycle. This is called:
     *   - once immediately to capture the "before" state, and
     *   - again inside the returned `finalize()` function to capture the "after" state.
     *
     * @returns A function that, when called, finalizes the capture and triggers animation.
     *
     * @example
     * const finalize = autoAnimate.captureFrame(() => draw());
     * mutateShapes();
     * finalize(); // triggers animation between captured states
     */
    captureFrame: (flushDraw: () => void) => {
      // clear any stale snapshots left over from previous abandoned frames
      snapshotMap.clear();

      const takeSnapshot = (state: 'before' | 'after') => {
        capturedSchemas = new Map();
        captureState = state;
        flushDraw();
        captureState = undefined;
      };

      takeSnapshot('before');

      return () => {
        takeSnapshot('after');

        const schemasCapturedInSnapshots = Array.from(snapshotMap).map(
          ([schemaId, snapshotStates]) => ({
            schemaId,
            beforeSchema: snapshotStates.before,
            afterSchema: snapshotStates.after,
          }),
        );

        for (const snapshot of schemasCapturedInSnapshots) {
          const { beforeSchema, afterSchema } = snapshot;

          // this shape was added
          if (!beforeSchema) {
            const schema = nullThrows(
              afterSchema,
              'after schema must be defined',
            );
            if (schema.shapeName === 'circle') {
              runAnimation(circleAdd, schema.id);
            }
            if (schema.shapeName === 'arrow') {
              runAnimation(arrowAdd, schema.id);
            }
            continue;
          }

          // this shape was removed
          if (!afterSchema) continue;

          // if a shapes schema has not changed between snapshots, we dont need to animate it
          const schemaDifference: DeepPartial<LooseSchemaWithName> | null =
            delta(beforeSchema, afterSchema);
          if (!schemaDifference) continue;

          // animation between shapes is not supported
          const { shapeName } = schemaDifference;
          if (shapeName) {
            console.warn(
              `shape with ID ${snapshot.schemaId} transformed from a ${beforeSchema.shapeName} to an ${afterSchema.shapeName}. Animating between shapes is unsupported and breaks the engine, therefore auto-animate has ignored it`,
            );
            continue;
          }

          const schemaPropNames = Object.keys(
            schemaDifference,
          ) as EverySchemaPropName[];

          const supportedSchemaProperties = schemaPropNames.filter((name) =>
            AUTO_ANIMATED_PROPERTIES.has(name),
          );

          const timelineValues = supportedSchemaProperties.map(
            (name): CreateTimelineValue => ({
              schemaPropertyName: name,
              startValue: beforeSchema[name],
              endValue: afterSchema[name],
            }),
          );

          const timeline = createTimeline(
            afterSchema.shapeName,
            timelineValues,
          );

          runAnimation(timeline, afterSchema.id);
        }

        snapshotMap.clear();
      };
    },
  };
};
