name: CI
on:
 pull_request:
jobs:
 check:
   runs-on: ubuntu-22.04
   steps:
     - uses: actions/checkout@v4
     - name: Install pnpm
       uses: pnpm/action-setup@v4
       with:
         version: latest
     - name: Install Node
       uses: actions/setup-node@v4
       with:
         node-version: 'lts/*'
         cache: 'pnpm'
     - name: Install dependencies
       run: pnpm install --frozen-lockfile
       working-directory: ./packages/client
     - name: Run check
       run: pnpm run check
       working-directory: ./packages/client
